# AgentOS Markdown Linting Configuration

# Default state for all rules
default: true

# Specific rule configurations
MD003:
  # Header style
  style: "atx"

MD007:
  # Unordered list indentation
  indent: 2

MD013:
  # Line length
  line_length: 120
  code_blocks: false
  tables: false
  headings: false

MD024:
  # Multiple headers with the same content
  allow_different_nesting: true

MD025:
  # Multiple top level headers in the same document
  front_matter_title: "^\\s*title\\s*[:=]"

MD026:
  # Trailing punctuation in header
  punctuation: ".,;:!?"

MD029:
  # Ordered list item prefix
  style: "ordered"

MD033:
  # Allow inline HTML
  allowed_elements: ["br", "sub", "sup", "kbd", "img"]

MD034:
  # Bare URL used
  # Disabled to allow bare URLs in documentation
  enabled: false

MD036:
  # Emphasis used instead of a header
  punctuation: ".,;:!?。，；：！？"

MD041:
  # First line in file should be a top level header
  front_matter_title: "^\\s*title\\s*[:=]"

MD046:
  # Code block style
  style: "fenced"

MD048:
  # Code fence style
  style: "backtick"