version: '3.8'

services:
  # Main development environment
  agentos-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: agentos-dev
    volumes:
      - .:/workspace
      - agentos-cache:/workspace/.cache
      - agentos-gradle:/root/.gradle
      - agentos-android-sdk:/opt/android-sdk
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - ANDROID_SDK_ROOT=/opt/android-sdk
      - PATH=/opt/android-sdk/tools:/opt/android-sdk/platform-tools:$PATH
    ports:
      - "5037:5037"  # ADB
      - "8080:8080"  # Development server
      - "3000:3000"  # Documentation server
    working_dir: /workspace
    tty: true
    stdin_open: true
    privileged: true  # Required for emulator
    devices:
      - /dev/kvm:/dev/kvm  # Hardware acceleration for emulator

  # AOSP build environment
  aosp-builder:
    build:
      context: .
      dockerfile: docker/Dockerfile.aosp
    container_name: aosp-builder
    volumes:
      - .:/workspace
      - aosp-source:/aosp
      - aosp-ccache:/ccache
    environment:
      - CCACHE_DIR=/ccache
      - USE_CCACHE=1
      - CCACHE_MAXSIZE=50G
    working_dir: /workspace
    tty: true
    stdin_open: true

  # Plugin development environment
  plugin-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.plugin-dev
    container_name: plugin-dev
    volumes:
      - .:/workspace
      - plugin-node-modules:/workspace/src/plugin-framework/sdk/node_modules
    ports:
      - "3001:3000"  # Plugin dev server
      - "8081:8080"  # Plugin testing server
    working_dir: /workspace/src/plugin-framework
    tty: true
    stdin_open: true

  # Documentation server
  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile.docs
    container_name: agentos-docs
    volumes:
      - ./docs:/docs
      - ./README.md:/docs/index.md
    ports:
      - "3002:3000"
    environment:
      - DOCS_PORT=3000
    command: ["mkdocs", "serve", "--dev-addr=0.0.0.0:3000"]

  # Testing environment
  test-runner:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    container_name: agentos-test
    volumes:
      - .:/workspace
      - test-reports:/workspace/test-reports
    environment:
      - CI=true
      - COVERAGE_REPORT=true
    working_dir: /workspace
    profiles: ["testing"]

  # Security scanning
  security-scanner:
    image: securecodewarrior/docker-security-scanner:latest
    container_name: agentos-security
    volumes:
      - .:/workspace
      - security-reports:/reports
    working_dir: /workspace
    profiles: ["security"]

volumes:
  agentos-cache:
    driver: local
  agentos-gradle:
    driver: local
  agentos-android-sdk:
    driver: local
  aosp-source:
    driver: local
  aosp-ccache:
    driver: local
  plugin-node-modules:
    driver: local
  test-reports:
    driver: local
  security-reports:
    driver: local

networks:
  default:
    name: agentos-network